services:
  - type: web
    name: clip-search-streamlit
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port $PORT --server.address 0.0.0.0"
    plan: free
    autoDeploy: true
